ALTER TABLE REPORTS_DEF_XML MODIFY
(REPORTDEFID VARCHAR2 (255));

ALTER TABLE REPORTS_DEF_XML
DROP COLUMN
 XMLFILE;

ALTER TABLE REPORT_XSL_FILE
DROP COLUMN
XSLFILE;

ALTER TABLE REPORTS_DEF_XML
ADD 
XMLFILE BLOB NOT NULL;

ALTER TABLE REPORT_XSL_FILE
ADD 
XSLFILE BLOB NOT NULL;
